application: hellokdb
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: templates/css
  
- url: /img
  static_dir: templates/img
  
- url: /js
  static_dir: templates/js
  
- url: /static
  static_dir: static

- url: /.*
  script: blog.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2                                                                  
  version: latest